# Site settings
title: Outright Analytics
email: info@outrightanalytics.com
description: Outright Analytics is your dedicated expert in a world of data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.outrightanalytics.com/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

remote_theme: dieghernan/chulapa
